import { Header } from '@/components/header'
import { Providers } from '@/providers/providers'
import type { Metadata } from 'next'
import { M_PLUS_Rounded_1c } from 'next/font/google'
import './globals.css'

const inter = M_PLUS_Rounded_1c({
	subsets: ['cyrillic'],
	weight: ['100', '300', '400', '500', '700', '800', '900'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>
					<div className='bg-[#07080a]'>
						{/* <AnimatedProgressBar> */}
						<div className=''>
							<div className='max-w-[1440px] mx-auto pt-10'>
								<Header />
							</div>
							<div className=''>{children}</div>
						</div>
						{/* </AnimatedProgressBar> */}
					</div>
				</Providers>
			</body>
		</html>
	)
}
